services:
  web-scraper:
    image: karthiksenthil2803/get-your-guide-web-scraper:latest
    ports:
      - "8180:8180" # Map container port 3000 to host port 3000
    environment:
      - MONGO_URI=mongodb://mongo:27017/get-your-guide
      - PORT=8180 # App port

  mongo:
    image: mongo:8.0.6 # Use the official MongoDB image
    container_name: mongo
    ports:
      - "27017:27017" # Expose MongoDB on port 27017
    volumes:
      - mongo-data:/data/db # Persist MongoDB data

volumes:
  mongo-data: